steps:
  # Step 1: Install dependencies using the official Node 18 image
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the Next.js application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Step 3: Build the Docker image and push it to Google Container Registry
  # Replace 'my-personal-website' with your preferred image name
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/my-blog-417504/my-blog:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/my-blog-417504/my-blog:$SHORT_SHA']

  # Step 4: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'demo-service' # This is your Cloud Run service name
      - '--image=gcr.io/my-blog-417504/my-blog:$SHORT_SHA'
      - '--allow-unauthenticated' # Remove this if you want to require authentication
      - '--region=us-central1'
      - '--platform=managed'
      - '--tag=preview-$SHORT_SHA'
    env:
      - 'CLOUDSDK_CORE_DISABLE_PROMPTS=1'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'


# Optional: specify options like logging
options:
  logging: CLOUD_LOGGING_ONLY